### ISSUE TITLE
what does it do?

### ISSUE THREAD

**Issue by ukmoose** [SergiuToporjinschi/rf-command#1]
thanks for creating a node for node-red. Could you put some more details in the README e.g.what does the node do, what hardware you need to use it?

Many thanks!

**Comment by SergiuToporjinschi** [comment]
I've just created the repo. currently it has only the node-red interface.
Is a node-red project to send a command via radio 433 from a raspberry pi.

**Comment by ukmoose** [comment]
As you’ve included the node-red keyword I assumed it was ready for use? As per the docs https://nodered.org/docs/creating-nodes/packaging

as it is now listed on flows.node-red.org

**Comment by SergiuToporjinschi** [comment]
Sorry, I did not know about that key word. I will remove it

**Comment by ukmoose** [comment]
no problem! I’ll look forward to trying out the node when you have finished it

**Comment by SergiuToporjinschi** [comment]
me too :))
I have a version for arduino ... but for my IOT, on RF I need it on rapsberry because I will have one single emitter for the entire house and all utilities.

**Comment by SergiuToporjinschi** [comment]
Now is a functional code. 
Have fun and let me know how is it for you.
